const Data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/products/Nike_Woman_Tshirt.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Puma Red Tight",
      category: "Shirts",
      image: "/images/products/puma_women_tight.png",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Nike Short",
      category: "Shorts",
      image: "/images/products/nike_woman_short.png",
      price: 160,
      brand: "Nike",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Nike tight",
      category: "Tights",
      image: "/images/products/nike_tight.png",
      price: 180,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Puma Jacket",
      category: "Jacket",
      image: "/images/products/puma_women_jacket.png",
      price: 180,
      brand: "Puma",
      rating: 3.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "6",
      name: "Under Armour Jacket",
      category: "Jacket",
      image: "/images/products/underarmour_women_jacket.png",
      price: 180,
      brand: "Under Armour",
      rating: 3.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "7",
      name: "Reebok Croptop",
      category: "Croptop",
      image: "/images/products/reebok_croptop.png",
      price: 180,
      brand: "Reebok",
      rating: 3.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "8",
      name: "Reebok Sweatshirt",
      category: "Sweatshirt",
      image: "/images/products/reebok_women_sweat.png",
      price: 180,
      brand: "Reebok",
      rating: 3.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "9",
      name: "Adidas T-shirt",
      category: "T-shirt",
      image: "/images/products/adidas_women_tshirt.jpg",
      price: 180,
      brand: "Adidas",
      rating: 3.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "10",
      name: "Adidas Panth",
      category: "Shirts",
      image: "/images/products/man/adidas_man_pantolon.jpg",
      price: 120,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "11",
      name: "Adidas Man SweatShirt",
      category: "Sweatshirt",
      image: "/images/products/man/adidas_man_sweat.jpg",
      price: 120,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "12",
      name: "Adidas Tshirt",
      category: "T-shirt",
      image: "/images/products/man/adidas_man_tshirt.jpg",
      price: 160,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "13",
      name: "Adidas Yellow Jacket",
      category: "Jacket",
      image: "/images/products/man/adidas_man_yellowjacket.jpg",
      price: 180,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "14",
      name: "Columbia Jacket",
      category: "Jacket",
      image: "/images/products/man/columbia_man_jacket.jpg",
      price: 180,
      brand: "Columbia",
      rating: 3.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "15",
      name: "New Balance Panth",
      category: "Panth",
      image: "/images/products/man/newbalance_man_pantolon.jpg",
      price: 180,
      brand: "New Balance",
      rating: 3.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "16",
      name: "Red T-shirt",
      category: "Croptop",
      image: "/images/products/man/nike_man_red_t-shirt.jpg",
      price: 180,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "17",
      name: "Nike Top",
      category: "Top",
      image: "/images/products/man/nike_man_top.jpg",
      price: 180,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "18",
      name: "Reebok T-shirt",
      category: "T-shirt",
      image: "/images/products/man/reebok_man_Tshirt.jpg",
      price: 180,
      brand: "Reebok",
      rating: 3.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "19",
      name: "Adidas Bag",
      category: "Bag",
      image: "/images/products/accesories/adidas_bag.jpg",
      price: 120,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "20",
      name: "Guess Wallet",
      category: "Wallet",
      image: "/images/products/accesories/guess_wallet.jpg",
      price: 120,
      brand: "Guess",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "21",
      name: "Under Armour Bag",
      category: "Bag",
      image: "/images/products/accesories/underarmour_bag.jpg",
      price: 160,
      brand: "Under Armour",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "22",
      name: "Brown Guess Belt",
      category: "Belt",
      image: "/images/products/accesories/brown_belt.jpg",
      price: 180,
      brand: "Guess",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "23",
      name: "Puma Hat",
      category: "Hat",
      image: "/images/products/accesories/puma_hat.jpg",
      price: 180,
      brand: "Puma",
      rating: 3.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "24",
      name: "Vans Bag",
      category: "Bag",
      image: "/images/products/accesories/Vans_bag.jpg",
      price: 180,
      brand: "Vans",
      rating: 3.5,
      numReviews: 10,
      description: "High quality product",
    },
  ],
};
export default Data;
